declare module "@postlight/mercury-parser";
declare module "article-parser";
declare module "readability";
declare module "request";
declare module "morgan";
declare module "cors";
declare module "errorhandler";
declare module "jsdom";
declare module "html-to-text";